---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - "{{ docker_old_versions_Debian }}"

- name: Install role dependencies.
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - "{{ docker_dependencies_Debian }}"

- name: Add Docker apt key.
  apt_key:
    url: "{{ apt_key_url }}"
    id: "{{ apt_key_id }}"
    state: present
  register: add_repository_key
  when:
    - apt_key_url != ''

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  when:
    - docker_apt_repository != ''
