---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: true
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: centos7
    image: ultransible/centos_7_systemd:v1
    pre_build_image: true
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
  - name: debian8
    image: ultransible/debian_8_systemd:v1
    pre_build_image: true
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
  - name: debian9
    image: ultransible/debian_9_systemd:v1
    pre_build_image: true
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

