---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: true
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: centos7
    image: ultransible/centos_7_systemd:v1
    command: /usr/lib/systemd/systemd
     pre_build_image: true
     volume_mounts:
       - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
     privileged: true
  -  image: ultransible/debian_9_systemd:v1
     pre_build_image: true
     volume_mounts:
       - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
     privileged: true
  - name: ubuntu18
    image: ultransible/ubuntu_18_04_systemd:v1
    pre_build_image: true
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
