---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: true
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
  - name: ${MOLECULE_DISTRO_NAME}
    image: ultransible/${MOLECULE_DISTRO}
    command: /usr/lib/systemd/systemd
    pre_build_image: true
    volume_mounts:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
